### ISSUE TITLE
Mojopkg GH action

### ISSUE THREAD

**Issue by Moosems** [saviorand/lightbug_http#25]
I could create some GH actions to auto run the tests and make mojopkg files for release :) I already created the script for another project and it's easy to adapt and low maintenance

**Comment by saviorand** [comment]
Hi, if you can would be much appreciated! Thanks for suggesting!

**Comment by Moosems** [comment]
Issue is that most binaries won't work on anyone else's computer

**Comment by saviorand** [comment]
Ah, maybe then we can ignore binaries for now

**Comment by Moosems** [comment]
mojopkg files are release files anyway so it's close enough :)

**Comment by saviorand** [comment]
@Moosems it's okay, I'll check and fix/add the action to the main repo today. Thanks for making it!
