### ISSUE TITLE
The server when restarted quickly gives message "Binding socket failed. Wait a few seconds and try again?" then the program continues as usual, like the error never happened

### ISSUE THREAD

**Issue by kazifarhan199** [saviorand/lightbug_http#38]
**Describe the bug**
When stopping the server and restarting, it indicates the server is listening, but the server is actually down.

**To Reproduce**
1. Clone the repository: git clone https://github.com/saviorand/lightbug_http.git
2. Navigate to the directory: cd lightbug_http
3. Start the server: mojo lightbug.🔥
4. Open localhost:8080 in a browser.
5. Stop the server: ctrl+c
6. Restart the server: mojo lightbug.🔥

**Expected behavior**
After displaying the message *"Binding socket failed. Wait a few seconds and try again?"*, the program should either exit or wait a few seconds and then start listening again. Currently, it prints *"🔥🐝 Lightbug is listening on http://0.0.0.0:8080/ Ready to accept connections..."* but attempting to access localhost:8080 in the browser results in an "Unable to connect" error.

**Screenshots**
<img width="794" alt="Screenshot 2024-05-18 at 7 36 53 PM" src="https://github.com/saviorand/lightbug_http/assets/26270542/09d68baa-7a7f-4874-8bb0-2071396e0db4">

**Desktop (please complete the following information):**
 - OS: Macos (14.4.1)
 - Browser: Firefox (125.0.3)
 - Version: not sure the commit id is 8fc335d

**Additional context**
I was trying to run the getting started

**Comment by saviorand** [comment]
Thanks for the detailed report! Should be fixed in https://github.com/saviorand/lightbug_http/pull/39 , just pull from main. Let me know if you have any feedback on the way this works now.
