### ISSUE TITLE
Refactor traits and how they're used

### ISSUE THREAD

**Issue by saviorand** [saviorand/lightbug_http#52]
Currently traits are not used properly. 
E.g. actual server implementations (`PythonServer` and `SysServer`) do not inherit from the `ServerTrait`.
This is because historically I've done things like return concrete implementations from a function that returns a trait, and this was removed from Mojo after a certain version.
Need to rethink how traits are used and in which cases they are valuable, and refactor accordingly.

**Comment by bgreni** [comment]
I think we can close this now since we removed the python implementation?

**Comment by saviorand** [comment]
@bgreni true, no longer relevant. Also don't think this will come up in the future, we already use traits for things like service definitions, and for things like server they're probably an overkill. Closing this now
